version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - ./local/pg:/var/lib/postgresql/data
      - ./sql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
